# Generated by Django 5.0.4 on 2024-06-15 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ticket_user_userphonenumber_alter_user_userfirstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketCreationDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketCreator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketTechnician',
            field=models.IntegerField(default=0),
        ),
    ]
