# Generated by Django 5.0.4 on 2024-06-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ticket_ticketstatus_alter_ticket_ticketcreationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
