# Generated by Django 5.0.4 on 2024-06-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ticket_ticketcreator_alter_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketCreator',
            new_name='userID',
        ),
    ]
