# Generated by Django 5.0.4 on 2024-06-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_ticketcreator_ticket_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='userID',
            new_name='ticketCreator',
        ),
    ]
