# Generated by Django 5.0.4 on 2024-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_userid_ticket_ticketcreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketDescription',
            field=models.TextField(default='No data', max_length=255),
        ),
    ]
