# Generated by Django 5.0.4 on 2024-06-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_ticketcreator_ticket_ticketcreator_dupa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticketCreator_dupa',
            new_name='ticketCreator',
        ),
    ]
