# Generated by Django 5.0.4 on 2024-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_ticketcreator_dupa_ticket_ticketcreator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketDescription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketTitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='userFirstName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userLastName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='userLogin',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPassword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
