# Generated by Django 5.0.4 on 2024-06-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_ticket_ticketdescription_alter_ticket_ticketid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketCreator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='myapp.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketTechnician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='myapp.user'),
        ),
    ]
