# Generated by Django 5.0.4 on 2024-06-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_ticket_tickettechnician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userLogin',
            field=models.CharField(max_length=255),
        ),
    ]
