# Generated by Django 5.0.4 on 2024-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.IntegerField(default=1),
        ),
    ]
