# Generated by Django 5.0.4 on 2024-06-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_comment_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='test',
        ),
    ]
