# Generated by Django 5.0.4 on 2024-06-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_test_remove_comment_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
