# Generated by Django 5.0.4 on 2024-06-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userRole',
            field=models.CharField(max_length=255),
        ),
    ]
