# Generated by Django 5.0.4 on 2024-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticketDescription',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='userLogin',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
